name: Pipeline
run-name: Running check ups
on: [push]
jobs:
  Hello-World-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          pnpm-version: "10.27.0"
      - run: ./deliverables/lab02/lab2.sh
